backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "artworks"
    label: "Artworks — 작품 아카이브"
    folder: "data/artworks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "string", default: "2025" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "reports"
    label: "Aesthetic Reports — 미학 보고서"
    folder: "data/reports"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Report Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
